name: ci/cd
on:
  push:
    tags:
      - '*'
jobs:
  gofsud-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the version
        id: get_version
        run: |
          git fetch --prune --unshallow
          echo ::set-output name=BRANCH::$(echo $(git branch --show-current | sed -r 's,/,-,g'))
          echo ::set-output name=REV::$(git rev-parse --short HEAD)
          echo ::set-output name=VERSION::$(git describe --tags)
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            theagentk/gofsud:latest
            theagentk/gofsud:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            VCS_TAG=${{ steps.get_version.outputs.VERSION }}
            GO_IMAGE_VERSION=1.15.5-alpine
            DISTROLESS_IMAGE=gcr.io/distroless/static
            DISTROLESS_VERSION=nonroot
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
