name: ci

on:
  push: 
    branches:
      - feat/docker-actions

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: theagentk/gofsud:dev
          build-args: |
            GO_IMAGE_VERSION=1.15.5-alpine
            DISTROLESS_IMAGE=gcr.io/distroless/static
            DISTROLESS_VERSION=nonroot

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
